language: ruby
cache:
  directories:
    - vendor/bundle
rvm:
  - "2.6.2"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
addons:
  postgresql: "9.3"
  chrome: stable
install: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
